[theme]
# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = "light"

# Primary accent color for interactive elements.
primaryColor="#007777"

# Background color for the main content area.
backgroundColor="#FFFFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor="#F7F7F7"

# Color used for almost all text.
textColor="#000000"

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
font="sans serif"

[server]
# The port where the server will listen for browser connections.
port = 80

# The base path for the URL where Streamlit should be served from.
baseUrlPath = "snowflake-catalog"

# List of folders that should not be watched for changes. This
# impacts both "Run on Save" and @st.cache.

# Relative paths will be taken as relative to the current working directory.

# Example: ['/home/user1/env', 'relative/path/to/folder']

# Default: []
folderWatchBlacklist = []

# Change the type of file watcher used by Streamlit, or turn it off
# completely.

# Allowed values:
# * "auto"     : Streamlit will attempt to use the watchdog module, and
#                falls back to polling if watchdog is not available.
# * "watchdog" : Force Streamlit to use the watchdog module.
# * "poll"     : Force Streamlit to always use polling.
# * "none"     : Streamlit will not watch files.

# Default: "auto"
fileWatcherType = "auto"

# Enables support for Cross-Origin Resource Sharing (CORS) protection, for
# added security.

# Due to conflicts between CORS and XSRF, if `server.enableXsrfProtection` is
# on and `server.enableCORS` is off at the same time, we will prioritize
# `server.enableXsrfProtection`.

# Default: true
enableCORS = true

# Enables support for Cross-Site Request Forgery (XSRF) protection, for added
# security.

# Due to conflicts between CORS and XSRF, if `server.enableXsrfProtection` is
# on and `server.enableCORS` is off at the same time, we will prioritize
# `server.enableXsrfProtection`.

# Default: true
enableXsrfProtection = true

# Max size, in megabytes, for files uploaded with the file_uploader.

# Default: 256
maxUploadSize = 256

# Server certificate file for connecting via HTTPS.
# Must be set at the same time as "server.sslKeyFile".

# ['DO NOT USE THIS OPTION IN A PRODUCTION ENVIRONMENT. It has not gone through
# security audits or performance tests. For the production environment, we
# recommend performing SSL termination by the load balancer or the reverse
# proxy.']
# sslCertFile =

# Cryptographic key file for connecting via HTTPS.
# Must be set at the same time as "server.sslCertFile".

# ['DO NOT USE THIS OPTION IN A PRODUCTION ENVIRONMENT. It has not gone through
# security audits or performance tests. For the production environment, we
# recommend performing SSL termination by the load balancer or the reverse
# proxy.']
# sslKeyFile =

[logger]
level = "error"

[client]
toolbarMode = "minimal"